### ISSUE TITLE
Allow configuration of executable and/or pick it up from the bin definition in Cargo.toml

### ISSUE THREAD

**Issue by naturalethic** [DioxusLabs/cli#19]
`executable` is picked up from the library name, but in my case the executable name is different.

Make it possible to configure this name, or pick it up from the configuration in Cargo.toml.

Example:
```toml
[lib]
name = "foo_web"
path = "src/lib/mod.rs"

[[bin]]
name = "foo-web"
path = "src/main/mod.rs"
```

Executable name should be `foo-web`.
