### ISSUE TITLE
Allow configuring a package directory

### ISSUE THREAD

**Issue by naturalethic** [DioxusLabs/cli#20]
Configuration should allow specifying a sub-crate for the web project.

```toml
[application]
package = "my-sub-crate"
```
